### ISSUE TITLE
About the Config

### ISSUE THREAD

**Issue by Hansmic** [hillelcoren/mudeo#1]
Hi, am a little lost  pertaining to the env.dart 
first, api_url  and api secret, do i have to edit it to mine personal or uses the one you have provided,
and can't really find sentry dns in any of the folder, please am i missing something. i really do loved this project.

**Comment by hillelcoren** [comment]
Hi, you'd need to setup an instance of the backend server to test the app.

https://github.com/turbo124/mudeo

**Comment by Hansmic** [comment]
Thanks Coren for getting back to me, I would do that!!!!

**Comment by Hansmic** [comment]
Hello, is there a way we have documentation on https://github.com/turbo124/mudeo, am literally lost doe

**Comment by hillelcoren** [comment]
What are your intentions with the codebase?

**Comment by Hansmic** [comment]
Am high school teacher, am just trying to encourage my students and my kids

**Comment by Hansmic** [comment]
My intentions( to understood and be able to explained to my kids)

**Comment by hillelcoren** [comment]
Understood. Sorry, I don't have any documentation to share.

**Comment by Hansmic** [comment]
I do really appreciate for reaching out doe.
