### ISSUE TITLE
Videos intermittently will not save

### ISSUE THREAD

**Issue by dylanm312** [hillelcoren/mudeo#2]
I am able to launch the new song screen and start recording a video, but about 70% of the time, when I press the stop button to save the take, it deletes the video instead of saving it. This obviously makes the app unusable. Stats below:

* OS: Android 10 build QQ3A.200805.001
* Phone: Google Pixel 2XL
* App version: 0.0.45

Feel free to ping me if you need more info. This is a great app idea, and I haven't seen many solutions out there, so I hope you can fix this bug so I can start making music! :)

**Comment by dylanm312** [comment]
@hillelcoren I saw your reply on the Play Store but I can't figure out how to reply there, so I'm gonna do it here instead. To answer your questions:

- I don't see any discernable pattern yet. I'll keep trying and see if I can identify something. Happy to send logs from my phone if that would help.
- I am using the latest version of the app, 0.0.45.

**Comment by hillelcoren** [comment]
Thanks for your feedback! I haven't been able to replicate the problem which makes it much more difficult to track down. I don't think there would be any logs for this, we track errors server side but I haven't seen anything related. 

Do you see the problem when saving the first track or when recording secondary tracks? The stop button will only save for the first track, for secondary tracks it acts as a 'cancel recording' button.

**Comment by dylanm312** [comment]
Good question. I see the problem with the first track. It just takes me straight back to the initial recording screen as if I never recorded anything in the first place. Let me see if I can find a screen recording app so I can demonstrate.

**Comment by dylanm312** [comment]
Of course now that I'm recording my screen it works perfectly 😂 maybe it was just a fluke? I'll try a few more times over the next few days and see if I can get it to do it again. Also I'm gonna go back and fix my review since this could very well be a case of PEBCAK lol. Again I am really happy you made this app - been looking for something like this for a long time and I was surprised that no one had come out with something like this.

**Comment by hillelcoren** [comment]
Thanks for trying again! If you're able to reproduce the problem let me know, I realize it can be frustrating to finish performing for the track not to be recorded.

**Comment by dylanm312** [comment]
The app has been reliably saving videos for about a week now. Closing this issue.
