### ISSUE TITLE
Recorded video is very dark

### ISSUE THREAD

**Issue by dylanm312** [hillelcoren/mudeo#3]
I found another bug that I actually WAS able to [screen record](https://photos.app.goo.gl/prZ7PLfeXz8mFmFp7) this time! When I hit the record button, the camera view goes dark, and the recorded footage that comes out after pressing stop is also very dark. As you can see in the video, my room is fairly well-lit, and the viewfinder displays normally before I press the record button. Only after I press record does it darken as shown in the screen recording.

**Comment by hillelcoren** [comment]
Thanks for reporting this!

- Does it record better when using the phone's built in camera app?

- Is there a difference in the flash behavior?

**Comment by dylanm312** [comment]
Yes, it records normally using the built-in camera. I don't see an option in the app to change the flash setting. However, I have discovered a few things:
* The camera works correctly when using the rear camera. It only gets dark as shown in the video when using the front camera.
* If I switch from front to rear camera while recording and then press Stop, I get an error:
 `CameraException(No video is recording, stopVideoRecording was called when no video is recording.)`

**Comment by hillelcoren** [comment]
Thanks for the info!

**Comment by hillelcoren** [comment]
Could be related to this issue: https://github.com/flutter/flutter/issues/55284#issuecomment-619352794

**Comment by dylanm312** [comment]
> 
> 
> Could be related to this issue: [flutter/flutter#55284 (comment)](https://github.com/flutter/flutter/issues/55284#issuecomment-619352794)

That looks like it might be it. Good find! 😄 Hopefully the folks at flutter are able to fix this at some point.

**Comment by jtkeyva** [comment]
@dylanm312 or @hillelcoren 
any news on this? seems dark on iphone 12
thanks

**Comment by hillelcoren** [comment]
I'm not sure, I'm only aware of this issue affecting Android devices.
